server:
 port: 8888
logging:
 level:
  root: INFO
  spordniar.cloud: DEBUG
  org.springframework.security: DEBUG
 config: classpath:logback.xml
spring:
 application:
  name: spordniar-cloud-config
 cloud:
  config:
   server:
    git:
     uri: https://github.com/zuiliushang/spordniar-cloud.git
     search-paths:
     - '{application}/src/main/resources'
     - '{application}/src/main/resources/config'
     #username: 
     #password:
 profiles:
  active: dev
management:
 security:
  enabled: false
endpoints:
 health:
  sensitive: false
security:
 basic:
  enabled: true
 user:
  name: spordniar
  password: admin
cors.allowed.origin: '*'
      