eureka:
 client:
  service-url:
   defaultZone: http://spordniar:admin@127.0.0.1:8761/eureka
 instance: 
  prefer-ip-address: true
  hostname: ${spring.cloud.client.ipAddress}
  instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
 rabbitmq:
  addresses: 192.168.203.128:5672
  username: admin
  password: admin
  publisher-confirms: true
  virtual-host: /