server:
 port: 9012   
spring:
 application:
  name: spordniar-cloud-aggregation
 cloud:
  config:
   uri: http://spordniar:admin@127.0.0.1:${config.port:8888}
 profiles:
  active: dev
eureka:
 client:
  service-url:
   defaultZone: http://spordniar:admin@127.0.0.1:8761/eureka
 instance:
  prefer-ip-address: true
  hostname: ${spring.cloud.client.ipAddress}
  instance-id: ${spring.cloud.client.ipAddress}:${server.port}
security:
 basic:
  enabled: true
 user:
  name: user
  password: password
management:
 security:
  enabled: false
rabbit.queue.persistent: true
logging:
 config: classpath:logback.xml
 level:
  root: info
  spordniar.cloud.aggregation: debug
  org.springframework.cloud: info