server:
 port: 8761
security:
 basic:
  enabled: true
 user:
  name: spordniar
  password: admin
logging:
 level:
  ROOT: INFO
spring:
 application:
  name: spordniar-cloud-eureka
 profiles:
  active: dev
 cloud:
  config:
   uri: http://spordniar:admin@127.0.0.1:${config.port:8888}